# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    - name: SFTP Deploy
    # You may pin to the exact commit or the version.
    # uses: wlixcc/SFTP-Deploy-Action@da88a4dbe95286266bbac3c0b2b8284048d20c8f
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        # username
        username: sftp
        # your sftp server
        server: birdey.com.au
        # your sftp server port, default to 22
        port: 22
        # will put all file under this path
        local_path: ./html/*
        # files will copy to under remote_path
        remote_path: /
        # connection via sftp protocol only
        sftp_only: true
        # This operation will delete all files in the remote path before upload. Please be careful set this to true
        delete_remote_files: false
        # SSH passsword，If a password is set, the secret key pair is ignored
        password: 74zrP3#,sq
